version: 0.2

phases:
  install:
    commands:
      - echo run npm install
      - npm cache clean --force
      - rm package-lock.json
      - npm install -g npm@10
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo build completed
